version: 2.1
jobs:
  build_test:
    steps:
      - checkout
      - run:
          name: install dependencies
          command: ./mvnw dependency:resolve
      - run:
          name: Maven install
          command: ./mvnw clean install

workflows:
  build_test:
    jobs:
      - build_test
